### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by gudata** [henrikkorsgaard/city-scanner#1]
Hello,
Are you planning to put the source code online?

**Comment by henrikkorsgaard** [comment]
Yes I do, soon. I'm testing a bit today and tomorrow, and then I might push a more finished version. 

Also, do I know you or how did you find the project?

**Comment by gudata** [comment]
Great! 
We do not know each other. I found the project while I was google-ing how to configure the wpa_supplicant to my home network.
